### ISSUE TITLE
Trouble making the Mysmartblinds Connection

### ISSUE THREAD

**Issue by SergeantPup** [docBliny/ha-mysmartblinds#2]
Hello,

I am trying to load your mysmartblinds driver for HA.  I have a mysmartblinds hub, I installed from HACs, confirmed the files are in the custom components section, and altered the secrets.yaml with my mysmartblinds login info.  Whenever I try to load it, I get an error:

Logger: homeassistant.setup
Source: setup.py:153
First occurred: 6:01:47 PM (1 occurrences)
Last logged: 6:01:47 PM

Setup failed for mysmartblinds: No setup or config entry setup function defined.

I know this is something stupid that I'm not doing.  I've read the readme multiple times and it either seems like it should be working or I'm missing a step.  Do you know what I'm missing?

Edit: while searching for something else, I accidentally found the entities for my blinds in HA.  I could open the controls but they said unavailable.  So this tells me for sure I have a connection but I have not been able to overcome the mysmartblinds setup error in the log to complete the setup.

**Comment by SergeantPup** [comment]
Hello, 
I got this working.  I jjust didn't know what I was doing as a HA newbie.  I just called/closed 4 blinds with my computer.  Something I've been trying to do for 2 years.  THANK YOU!

**Comment by gregmichael** [comment]
How did you get this working? I am facing the same issue...

**Comment by SergeantPup** [comment]
Hi,

I had mysmartblinds working for the better part of a year and there was a recent update that bricked everybody's hub (and subsequently this integration).  There's another thread and conversation about it here: https://github.com/docBliny/ha-mysmartblinds/issues/3

I think somebody started an MQTT version.  Mine are all still dead and I was going to follow up with the thread anyway.  Last I knew, the code owner did everything they could from this end to prepare the integration to work again but we were still waiting on a fix from MSB last I knew.
