### ISSUE TITLE
Unavailable

### ISSUE THREAD

**Issue by gregmichael** [docBliny/ha-mysmartblinds#4]
Installed via HACS and I can report that I am seeing my blinds showing up as entities, but I cannot control them: "Unavailable"

**Comment by docBliny** [comment]
Closing as duplicate of https://github.com/docBliny/ha-mysmartblinds/issues/3

**Comment by docBliny** [comment]
Closing as duplicate of https://github.com/docBliny/ha-mysmartblinds/issues/3
