### ISSUE TITLE
Installation instructions do not make sense

### ISSUE THREAD

**Issue by lthown** [docBliny/ha-mysmartblinds#5]
I have installed this github as a custom repo in HACS, when I go to add a device or integration in the HA webUI it responds with

```
This device cannot be added from the UI
You can add this device by adding it to your 'configuration.yaml'. See the documentation for more information.
```

I do have a file in /root/config/custom_components/mysmartblinds/secret.yaml along with the files that were installed as part of the HACS install and it has the correct username and password for mySmartBlinds

So... how do I get the mySmartBlinds devices to show up in HA?

**Comment by docBliny** [comment]
Sounds like your `secrets.yaml` is not in the correct place. See https://www.home-assistant.io/docs/configuration/secrets/ for the official instructions on that.

Additionally, the instructions for Home Assistant's `configuration.yaml` file are here: https://www.home-assistant.io/docs/configuration/

Both of the above files are part of Home Assistant and live in the Home Assistant `config` folder, not in the HACs folder.
